### PR TITLE
libbpf-cargo: Make clang version checking more flexible

### LINKED ISSUE #30: cargo libbpf build command failed
### symptoms

Fail to build if clang --version returns a string which unexpected format. 

expected 

```
clang version 10.0.0
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /bin
``` 

the string when the command fail.

```
Ubuntu clang version 11.0.1-++20201121072624+973b95e0a84-1~exp1~20201121063303.19
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /bin
```

And cargo libbpf build command returns following:

```
$ cargo libbpf build
/bin/clang is invalid: Error parsing major identifier
```

### clang 
installed from https://apt.llvm.org/groovy/pool/main/l/llvm-toolchain-11/

### kernel version
```
Linux shun159.localhost 5.9.8 #1 SMP Wed Nov 18 14:56:48 JST 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### lsb-release
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Ubuntu 20.10"
```

if you need further information, please let me know.

Regards

### PR DESCRIPTION
**Pull request by danobi**
Turns out distros change the upstream version string sometimes.

This closes #30 .

### CODE REVIEW

File: libbpf-cargo/src/build.rs [hunk 1]
```diff
@@ -165,6 +166,18 @@ fn check_progs(progs: &[UnprocessedProg]) -> Result<()> {
     Ok(())
 }
 
+fn extract_version(output: &str) -> Result<&str> {
+    let re = Regex::new(r"clang\s+version\s+(?P<version_str>\d+\.\d+\.\d+).*")?;
```
Comment (anakryiko) [inline libbpf-cargo/src/build.rs:170]: maybe add beginning of string matching (`^`)? and .* is probably not necessary, given this is a substring match

**Review by anakryiko — APPROVED** [review]
LGTM

File: libbpf-cargo/src/build.rs (hunk 1 above)
Comment (danobi) [reply libbpf-cargo/src/build.rs]: Can't add `^` b/c the ubuntu format adds "Ubuntu" to the front
